# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChargingTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChargingTest
  pod 'R_category'
  pod 'SnapKit', '~> 5.0.0'
  pod 'MJRefresh', '~> 3.2.0'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'Moya', '~> 13.0.1'
  pod 'Kingfisher', '~> 7.0.0'
  pod 'SwiftyJSON', '~> 5.0.0'
  pod 'Tiercel'
  pod 'SegementSlide', '3.0.1'
  
end
